### ISSUE TITLE
Problem at connection

### ISSUE THREAD

**Issue by asennoussi** [JDare/ClankBundle#26]
I'm using clank bundle and I want to test if socket server is running without problem 
I have set the configuration as follow :

```
# Clank Configuration
clank:
    web_socket_server:
        port: 8080        #The port the socket server will listen on
        host: domain.com #(optional) The host ip to bind to
```

the port 8080 is open and tested 
after adding the two js files : `autobahn.min.js` and `clank.js` I do the following :

```
var myClank = Clank.connect("wss://domain.com:8080"); // I use SSL

        myClank.on("socket/connect", function(session){
            //session is an Autobahn JS WAMP session.

            console.log("Successfully Connected!");
        })

        myClank.on("socket/disconnect", function(error){
            //error provides us with some insight into the disconnection: error.reason and error.code

            console.log("Disconnected for " + error.reason + " with code " + error.code);
        })
```

note that the server is already running with the command : 

```
php app/console clank:server
```

the problem is I can't get the success message in my console.. When I stop clank server , it outputs the failure message.
I don't know what's happening please help me ..
